fast-to-face/src/com/acc/model/AccDAO.java
package com.acc.model;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;

import com.cou.model.CouVO;

public class AccDAO implements AccDAO_interface {

	// 一個應用程式中,針對一個資料庫 ,共用一個DataSource即可
	private static DataSource ds = null;
	static {
		try {
			Context ctx = new InitialContext();
			ds = (DataSource) ctx.lookup("java:comp/env/jdbc/TestDB");
		} catch (NamingException e) {
			e.printStackTrace();
		}
	}

	private static final String INSERT_STMT = 
			"INSERT INTO account (accno, acc, accpsw, accrole, accname, accpic, accintro, accemail) VALUES (Acc_SEQ.NEXTVAL, ?, ?, ?, ?, ?, ?, ?)";
	private static final String GET_ALL_STMT = 
			"SELECT * FROM account order by accno";
	private static final String GET_ONE_STMT = 
			"SELECT * FROM account where accno = ?";
	private static final String DELETE = 
			"DELETE FROM account where accno = ?";
	private static final String UPDATE = 
			"UPDATE account set accname=?, accpic=?, accintro=?, accemail=? where accno = ?";
	
	
	//康縣加的
	private static final String GET_COUS_BY_ACCNO = 
			"select * from course where accno = ? and coustate != -1";
	//jie
	private static final String UPDATE_ACCPSW = 
			"UPDATE account set accpsw = ? where accno = ?";
	private static final String GET_account_password_STMT = 
			"SELECT * FROM account where acc = ? AND accpsw = ?";
	
	@Override
	public void insert(AccVO accVO) {

		Connection con = null;
		PreparedStatement pstmt = null;

		try {

			con = ds.getConnection();
			pstmt = con.prepareStatement(INSERT_STMT);  //新增一筆資料

			pstmt.setString(1, accVO.getAcc());
			pstmt.setString(2, accVO.getAccpsw());
			pstmt.setInt(3, accVO.getAccrole());
			pstmt.setString(4, accVO.getAccname());
			pstmt.setBytes(5, accVO.getAccpic());
			pstmt.setString(6, accVO.getAccintro());
			pstmt.setString(7, accVO.getAccemail());
			
			pstmt.executeUpdate();

		} catch (SQLException se) {
			throw new RuntimeException("A database error occured. "
					+ se.getMessage());
		} finally {
			if (pstmt != null) {
				try {
					pstmt.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (con != null) {
				try {
					con.close();
				} catch (Exception e) {
					e.printStackTrace(System.err);
				}
			}
		}

	}

	@Override
	public void update(AccVO accVO) {

		Connection con = null;
		PreparedStatement pstmt = null;

		try {

			con = ds.getConnection();
			pstmt = con.prepareStatement(UPDATE); 

			pstmt.setString(1, accVO.getAccname());
			pstmt.setBytes(2, accVO.getAccpic());
			pstmt.setString(3, accVO.getAccintro());
			pstmt.setString(4, accVO.getAccemail());
			pstmt.setInt(5, accVO.getAccno());
			pstmt.executeUpdate();

			// Handle any driver errors
		} catch (SQLException se) {
			throw new RuntimeException("A database error occured. "
					+ se.getMessage());
			// Clean up JDBC resources
		} finally {
			if (pstmt != null) {
				try {
					pstmt.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (con != null) {
				try {
					con.close();
				} catch (Exception e) {
					e.printStackTrace(System.err);
				}
			}
		}

	}

	@Override
	public void delete(Integer accno) {

		Connection con = null;
		PreparedStatement pstmt = null;

		try {

			con = ds.getConnection();
			pstmt = con.prepareStatement(DELETE); 
			pstmt.setInt(1, accno); 
			pstmt.executeUpdate();
		} catch (SQLException se) {
			throw new RuntimeException("A database error occured. "
					+ se.getMessage());
		} finally {
			if (pstmt != null) {
				try {
					pstmt.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (con != null) {
				try {
					con.close();
				} catch (Exception e) {
					e.printStackTrace(System.err);
				}
			}
		}

	}

	@Override
	public AccVO findByPrimaryKey(Integer accno) {

		AccVO accVO = null;
		Connection con = null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;

		try {

			con = ds.getConnection();
			pstmt = con.prepareStatement(GET_ONE_STMT);

			pstmt.setInt(1, accno);

			rs = pstmt.executeQuery();

			while (rs.next()) {
				accVO = new AccVO();
				accVO.setAccno(rs.getInt("accno"));
				accVO.setAcc(rs.getString("acc"));
				accVO.setAccpsw(rs.getString("accpsw"));
				accVO.setAccrole(rs.getInt("accrole"));
				accVO.setAccname(rs.getString("accname"));
				accVO.setAccpic(rs.getBytes("accpic"));
				accVO.setAccintro(rs.getString("accintro"));
				accVO.setAccemail(rs.getString("accemail"));
			}

		} catch (SQLException se) {
			throw new RuntimeException("A database error occured. "
					+ se.getMessage());
		} finally {
			if (rs != null) {
				try {
					rs.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (pstmt != null) {
				try {
					pstmt.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (con != null) {
				try {
					con.close();
				} catch (Exception e) {
					e.printStackTrace(System.err);
				}
			}
		}
		return accVO;
	}

	@Override
	public List<AccVO> getAll() {
		List<AccVO> list = new ArrayList<AccVO>();
		AccVO accVO = null;

		Connection con = null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;

		try {

			con = ds.getConnection();
			pstmt = con.prepareStatement(GET_ALL_STMT);  
			rs = pstmt.executeQuery();

			while (rs.next()) {
				accVO = new AccVO();
				accVO.setAccno(rs.getInt("accno"));
				accVO.setAcc(rs.getString("acc"));
				accVO.setAccpsw(rs.getString("accpsw"));
				accVO.setAccrole(rs.getInt("accrole"));
				accVO.setAccname(rs.getString("accname"));
				accVO.setAccpic(rs.getBytes("accpic"));
				accVO.setAccintro(rs.getString("accintro"));
				accVO.setAccemail(rs.getString("accemail"));
				list.add(accVO); 
			}

		} catch (SQLException se) {
			throw new RuntimeException("A database error occured. "
					+ se.getMessage());
		} finally {
			if (rs != null) {
				try {
					rs.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (pstmt != null) {
				try {
					pstmt.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (con != null) {
				try {
					con.close();
				} catch (Exception e) {
					e.printStackTrace(System.err);
				}
			}
		}
		return list;
	}
	
	
	//康縣加的
	@Override
	public Set<CouVO> getCousByAccno(Integer accno) {
		Set<CouVO> set = new LinkedHashSet<CouVO>();
		CouVO couVO = null;

		Connection con = null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;

		try {

			con = ds.getConnection();
			pstmt = con.prepareStatement(GET_COUS_BY_ACCNO);
			pstmt.setInt(1, accno);
			
			rs = pstmt.executeQuery();

			while (rs.next()) {				
				couVO = new CouVO();
				couVO.setCouno(rs.getInt("couno"));
				couVO.setCouname(rs.getString("couname"));
				couVO.setCouintro(rs.getString("couintro"));
				couVO.setCoupic(rs.getBytes("coupic"));
				couVO.setCoubadge(rs.getBytes("coubadge"));
				couVO.setCouprice(rs.getInt("couprice"));
				couVO.setCoudiscount(rs.getInt("coudiscount"));
				couVO.setCouishot(rs.getInt("couishot"));
				couVO.setAccno(rs.getInt("accno"));
				couVO.setCoustate(rs.getInt("coustate"));
				couVO.setProno(rs.getInt("prono"));
				couVO.setCouupdate(rs.getTimestamp("couupdate"));
				set.add(couVO);
			}

		} catch (SQLException se) {
			throw new RuntimeException("A database error occured. "
					+ se.getMessage());
		} finally {
			if (rs != null) {
				try {
					rs.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (pstmt != null) {
				try {
					pstmt.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (con != null) {
				try {
					con.close();
				} catch (Exception e) {
					e.printStackTrace(System.err);
				}
			}
		}
		return set;
	}
	
	
	
	@Override
	public void updatePsw(Integer accno, String accpsw) {

		Connection con = null;
		PreparedStatement pstmt = null;

		try {

			con = ds.getConnection();
			pstmt = con.prepareStatement(UPDATE_ACCPSW);

			pstmt.setString(1, accpsw);
			pstmt.setInt(2, accno);
			pstmt.executeUpdate();

		} catch (SQLException se) {
			throw new RuntimeException("A database error occured. "
					+ se.getMessage());
		} finally {
			if (pstmt != null) {
				try {
					pstmt.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (con != null) {
				try {
					con.close();
				} catch (Exception e) {
					e.printStackTrace(System.err);
				}
			}
		}
	}
	
	
	@Override
	public AccVO findByAccPsw(String acc, String accpsw) {

		AccVO accVO = null;
		Connection con = null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;

		try {

			con = ds.getConnection();
			pstmt = con.prepareStatement(GET_account_password_STMT);

			pstmt.setString(1, acc);
			pstmt.setString(2, accpsw);
			rs = pstmt.executeQuery();

			while (rs.next()) {
				accVO = new AccVO();
				accVO.setAccno(rs.getInt("accno"));
				accVO.setAcc(rs.getString("acc"));
				accVO.setAccpsw(rs.getString("accpsw"));
				accVO.setAccrole(rs.getInt("accrole"));
				accVO.setAccname(rs.getString("accname"));
				accVO.setAccpic(rs.getBytes("accpic"));
				accVO.setAccintro(rs.getString("accintro"));
				accVO.setAccemail(rs.getString("accemail"));
			}
			

		} catch (SQLException se) {
			throw new RuntimeException("A database error occured. "
					+ se.getMessage());
		} finally {
			if (rs != null) {
				try {
					rs.close();
				} catch (SQLException se) {
					se.printStackTrace(System.err);
				}
			}
			if (pstmt != null) {
				try {
					pstmt.close();

fast-to-face/WebContent/back/course_management/addCou.jsp
<%@page import="com.cou.model.CouVO"%>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="Big5"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<jsp:useBean id="proSvc" scope="page" class="com.pro.model.ProService"/>
<jsp:useBean id="accSvc" scope="page" class="com.acc.model.AccService"/>

<%
	CouVO couVO = (CouVO)request.getAttribute("couVO");

%>

<html>
	<head>
		<title>Insert title here</title>
		
		<!-- back shared file -->
		<script src="<%=request.getContextPath()%>/shared/js/jquery-1.11.1.min.js"></script>
		<script src="<%=request.getContextPath()%>/shared/js/jquery-ui.min.js"></script>		
		<link rel="stylesheet" href="<%=request.getContextPath()%>/shared/css/bootstrap.min.css">
		<link rel="stylesheet" href="<%=request.getContextPath()%>/shared/css/bootstrap-theme.min.css">
		<script src="<%=request.getContextPath()%>/shared/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="<%=request.getContextPath()%>/shared/css/back.css">
		<script src="<%=request.getContextPath()%>/shared/js/back.js"></script>
		
		<!-- self -->
		<script src="<%=request.getContextPath()%>/back/course_management/js/addCou.js"></script>
		<link rel="stylesheet" href="<%=request.getContextPath()%>/back/course_management/css/addCou.css">
		
		
	</head>
	<body>
		<%@ include file="/shared/pages/back_header_nav.file" %>
		<h2 class="backtitle">新增課程</h2>
		<ol class="breadcrumb">
		  	<li><a href="<%=request.getContextPath()%>/couManagement/cou.do?action=getCouList">課程管理</a></li>
		 	<li class="active">新增課程</li>
		</ol>  
		<c:if test="${not empty errorMsgs}">
			<font color='red'>請修正以下錯誤:
				<ul>
					<c:forEach var="message" items="${errorMsgs}">
					<li>${message}</li>
					</c:forEach>
				</ul>
			</font>
		</c:if>
		<form action="<%=request.getContextPath()%>/couManagement/cou.do?" method="post" enctype="multipart/form-data">
			<table class="borderless">
				<tr>
					<td>課程名稱</td>
					<td><input type="text" name="couname" value="<%= (couVO==null)? "": couVO.getCouname() %>" id="couname"/></td>
				</tr>
				<tr>
					<td>課程簡介</td>
					<td><textarea name="couintro" rows="10" cols="50" id="couintro"><%= (couVO==null)? "": couVO.getCouintro() %></textarea></td>
				</tr>
				<tr>
					<td>課程圖片</td>
					<td>
						<div id="previewPic" ></div>
						<input type="file" name="coupic" accept="image/*" id="uploadImage" onchange="previewPic(this)"/>
					</td>
				</tr>
				<tr>
					<td>徽章圖片</td>
					<td>
						<div id="previewBadge" ></div>
						<input type="file" name="coubadge" accept="image/*" id="uploadImage" onchange="previewBadge(this)"/>
					</td>
				</tr>
				<tr>
					<td>購買點數</td>
					<td><input type="text" name="couprice" value="<%= (couVO==null)? "": couVO.getCouprice() %>" id="couprice"/></td>
				</tr>
				<tr>
					<td>折扣點數</td>
					<td><input type="text" name="coudiscount" value="<%= (couVO==null)? "": couVO.getCoudiscount() %>" id="coudiscount"/></td>
				</tr>
				<tr>
					<td>授課老師</td>
					<td>
						<select name="accno">
							<c:forEach var="accVO" items="${accSvc.all}">
								<option value="${accVO.accno}" ${proVO.prono}" ${(accVO.accno==couVO.accno)? 'selected':'' }>${accVO.accname}</option>
							</c:forEach>
						</select>
					</td>
				</tr>
				<tr>
					<td>學程編號</td>
					<td>
						<select name="prono">
							<option value="">未分類
							<c:forEach var="proVO" items="${proSvc.all}">
								<option value="${proVO.prono}" ${(proVO.prono==couVO.prono)? 'selected':'' } >${proVO.prono}-${proVO.proname}</option>
							</c:forEach>						
						</select>
					</td>
				</tr>
				
			</table>
			<input type="submit" value="新增" />
			<button type="button" class="btn btn-warning btn-xs" id="magic_button2"><span class="glyphicon glyphicon-star"></span></button>		
			<input type="hidden" name="action" value="insert"/>
		</form>
		
		<script>
			$(function(){							
				$("#magic_button2").click(function(){									
					$("#couname").val("Android 網路服務與應用");
					$("#couintro").val("手機App採用AsyncTask方式連結Web服務以取得所需資料，並以Android UI元件呈現給使用者。為了達到跨平台需求，資料交換部分採用JSON。");
					$("#couprice").val("200");
					$("#coudiscount").val("180");
				});	
			});
		</script>
		
		<%@ include file="/shared/pages/back_footer.file" %> 
	</body>
</html>

fast-to-face/WebContent/back/course_management/couDetail.jsp
<%@page import="java.util.Set"%>
<%@page import="com.ass.model.AssVO"%>
<%@page import="com.content.model.*"%>
<%@page import="com.unit.model.*"%>
<%@page import="java.util.List"%>
<%@page import="com.cou.model.*"%>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="Big5"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>


<html>
	<head>
		<title>Insert title here</title>
		
		<!-- back shared file -->
		<script src="<%=request.getContextPath()%>/shared/js/jquery-1.11.1.min.js"></script>
		<script src="<%=request.getContextPath()%>/shared/js/jquery-ui.min.js"></script>		
		<link rel="stylesheet" href="<%=request.getContextPath()%>/shared/css/bootstrap.min.css">
		<link rel="stylesheet" href="<%=request.getContextPath()%>/shared/css/bootstrap-theme.min.css">
		<script src="<%=request.getContextPath()%>/shared/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="<%=request.getContextPath()%>/shared/css/back.css">
		<script src="<%=request.getContextPath()%>/shared/js/back.js"></script>
		
		<!-- self -->
		<link rel="stylesheet" href="<%=request.getContextPath()%>/back/course_management/css/couDetail.css">
	</head>
	<body>
		<%@ include file="/shared/pages/back_header_nav.file" %>		
		<h2 class="backtitle">${couVO.couname}</h2>
		<ol class="breadcrumb">
		  	<li><a href="<%=request.getContextPath()%>/couManagement/cou.do?action=getCouList">課程管理</a></li>
		 	<li class="active">${couVO.couname}</li>
		</ol>
		 
		<c:forEach var="unitVO" items="${unitVOSet}" varStatus="unitStatus">
		<table class="table table-bordered">
			<tr class="titleBgcolor">				
				<td colspan="5">
				<h2><small>單元${unitStatus.count}</small></h2>
				<h1>${unitVO.unitname}</h1>
				
				</td>
			</tr>
			<tr class="success">
				<td width="150">單元內容編號</td>
				<td width="150">類別</td>
				<td>名稱</td>
				<td width="150">排序</td>
				<td width="150"></td>			
			</tr>			
			<c:forEach var="conVO" items="${conVOSetList[unitStatus.index]}" varStatus="conStatus">
				<tr>
					<td>${conVO.conno}</td>
					<td>${conVO.contype}</td>
					<td style="text-align:left;">${conVO.conname}</td>
					<td>${conVO.conorder}</td>
					<td>
						<c:if test="${conVO.contype=='影片'||conVO.contype=='影片 '}">
							<button type="button" class="btn btn-default btn-sm" style="margin:10px 0px;padding:4px 10px;font-size:18px;" data-toggle="modal" data-target="#${conVO.conno}">查看影片</button>
							<div class="modal fade" id="${conVO.conno}" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
								<div class="modal-dialog modal-lg">				
									<div class="modal-content" >
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
											<h4 class="modal-title">${conVO.conno}&nbsp-&nbsp${conVO.contype}&nbsp&nbsp${conVO.conname}</h4>
										</div>
										<div class="modal-body">
											<video  width="865" controls >
												<source src="<%=request.getContextPath()%>/shared/video/${conVO.convideo}" type="video/mp4">
											</video>
										</div>
									</div>
								</div>
							</div>
							
			    		</c:if>
			    		<c:if test="${conVO.contype=='評量'||conVO.contype=='評量 '}">
							<button type="button" class="btn btn-default btn-sm" style="margin:10px 0px;padding:4px 10px;font-size:18px;" data-toggle="modal" data-target="#${conVO.conno}">查看評量</button>
							<div class="modal fade" id="${conVO.conno}" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
								<div class="modal-dialog modal-lg">				
									<div class="modal-content" >
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
											<h4 class="modal-title">${conVO.conno}&nbsp-&nbsp${conVO.contype}&nbsp&nbsp${conVO.conname}</h4>
										</div>
										<div class="modal-body">
							    			<c:forEach var="assVO" items="${assVOSetListList[unitStatus.index][conStatus.index]}" varStatus="assStatus">
							    			<table class="borderless">
							    				<tr>
							    					<th width="90">題目編號</th>
							    					<td>${assVO.assno}</td>
							    				</tr>
							    				<tr>
							    					<th>題目</th>
							    					<td>${assVO.assques}</td>
							    				</tr>
							    				<tr>
							    					<th>答案</th>
							    					<td>${assVO.assans}</td>
							    				</tr>
							    				<tr>
							    					<th>(A)</th>
							    					<td>${assVO.assansa}</td>
							    				</tr>
							    				<tr>
							    					<th>(B)</th>
							    					<td>${assVO.assansb}</td>
							    				</tr>
							    				<tr>
							    					<th>(C)</th>
							    					<td>${assVO.assansc}</td>
							    				</tr>
							    				<tr>
							    					<th>(D)</th>
							    					<td>${assVO.assansd}</td>
							    				</tr>				    			
							    			</table>
							    			<hr/>
							    			</c:forEach>
										</div>
									</div>
								</div>
							</div>
				    		
				    		
			    		</c:if>					
					</td>
				</tr>
			</c:forEach>
		</table>
		</c:forEach>
		
	<%@ include file="/shared/pages/back_footer.file" %>
	</body>
</html>

fast-to-face/WebContent/back/course_management/update_cou_input.jsp
<%@page import="com.cou.model.CouVO"%>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="Big5"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<% CouVO couVO = (CouVO)request.getAttribute("couVO"); %>
<jsp:useBean id="proSvc" scope="page" class="com.pro.model.ProService"/>
<jsp:useBean id="accSvc" scope="page" class="com.acc.model.AccService"/>

<html>
	<head>
		<title>Insert title here</title>
		
		<!-- back shared file -->
		<script src="<%=request.getContextPath()%>/shared/js/jquery-1.11.1.min.js"></script>
		<script src="<%=request.getContextPath()%>/shared/js/jquery-ui.min.js"></script>		
		<link rel="stylesheet" href="<%=request.getContextPath()%>/shared/css/bootstrap.min.css">
		<link rel="stylesheet" href="<%=request.getContextPath()%>/shared/css/bootstrap-theme.min.css">
		<script src="<%=request.getContextPath()%>/shared/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="<%=request.getContextPath()%>/shared/css/back.css">
		<script src="<%=request.getContextPath()%>/shared/js/back.js"></script>
		
		<!-- self -->
		<script src="<%=request.getContextPath()%>/back/course_management/js/update_cou_input.js"></script>
		<link rel="stylesheet" href="<%=request.getContextPath()%>/back/course_management/css/update_cou_input.css">
		
	</head>
	<body>
		<%@ include file="/shared/pages/back_header_nav.file" %>
		<h2 class="backtitle">編輯課程</h2>
		<ol class="breadcrumb">
		  	<li><a href="<%=request.getContextPath()%>/couManagement/cou.do?action=getCouList">課程管理</a></li>
		 	<li class="active">編輯課程</li>
		</ol>  
		<c:if test="${not empty errorMsgs}">
			<font color='red'>請修正以下錯誤:
				<ul>
					<c:forEach var="message" items="${errorMsgs}">
					<li>${message}</li>
					</c:forEach>
				</ul>
			</font>
		</c:if>
		<form action="<%=request.getContextPath()%>/couManagement/cou.do" method="post" enctype="multipart/form-data">
			<table class="borderless">
				<tr>
					<td>課程編號</td>
					<td><%= couVO.getCouno() %></td>
				</tr>
				<tr>
					<td>課程名稱</td>
					<td><input type="text" name="couname" value="<%= couVO.getCouname() %>"/></td>
				</tr>
				<tr>
					<td>課程簡介</td>
					<td><textarea name="couintro" rows="10" cols="50"><%= couVO.getCouintro() %></textarea></td>
				</tr>
				<tr>
					<td>課程圖片</td>
					<td>
						<div id="previewPic" >
							<img src="<%=request.getContextPath()%>/cou/cou.do?couno=<%= couVO.getCouno() %>&action=getCoupic" height="80"/>
						</div>
						<input type="file" name="coupic" accept="image/*" id="uploadImage" onchange="previewPic(this)"/>
					</td>
				</tr>
				<tr>
					<td>徽章圖片</td>
					<td>
						<div id="previewBadge" >
							<img src="<%=request.getContextPath()%>/cou/cou.do?couno=<%= couVO.getCouno() %>&action=getCoubadge" height="80"/>
						</div>
						<input type="file" name="coubadge" accept="image/*" id="uploadImage" onchange="previewBadge(this)"/>
					</td>
				</tr>
				<tr>
					<td>購買點數</td>
					<td><input type="text" name="couprice" value="<%= couVO.getCouprice() %>"/></td>
				</tr>
				<tr>
					<td>折扣點數</td>
					<td><input type="text" name="coudiscount" value="<%= couVO.getCoudiscount() %>"/></td>
				</tr>
				<tr>
					<td>授課老師</td>
					<td>
						<select name="accno">
							<c:forEach var="accVO" items="${accSvc.all}">
								<option value="${accVO.accno}" ${proVO.prono}" ${(accVO.accno==couVO.accno)? 'selected':'' }>${accVO.accname}</option>
							</c:forEach>
						</select>
					</td>
				</tr>
				<tr>
					<td>課程狀態</td>
					<td>
						<select name="coustate"   >
							<option value="0" <%= (couVO.getCoustate()==0)?"selected":"" %>>未審核</option>
							<option value="1" <%= (couVO.getCoustate()==1)?"selected":"" %>>待審核</option>
							<option value="2" <%= (couVO.getCoustate()==2)?"selected":"" %>>已審核</option>
							<option value="3" <%= (couVO.getCoustate()==3)?"selected":"" %>>上線中</option>
						</select>
					</td>				
				</tr>
				<tr>
					<td>學程編號</td>
					<td>
						<select name="prono">
							<option value="">未分類</option>
							<c:forEach var="proVO" items="${proSvc.all}">
								<option value="${proVO.prono}" ${(proVO.prono==couVO.prono)? 'selected':'' } >${proVO.prono}-${proVO.proname}</option>
							</c:forEach>						
						</select>
					</td>
				</tr>				
			
			</table>
			<input type="submit" value="儲存" />
			<input type="hidden" name="action" value="update"/>
			<input type="hidden" name="couno" value="<%= couVO.getCouno() %>" />					
			<input type="hidden" name="requestURL" value="${requestURL}" />					
			<input type="hidden" name="whichPage" value="${whichPage}" />
		</form>
	<%@ include file="/shared/pages/back_footer.file" %>
	</body>
</html>